# Generated by Django 5.2.17 on 2026-10-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('f', 'Feminin'), ('m', 'Masculin'), ('autre', 'Autre')])),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=120)),
            ],
            options={
                'verbose_name': 'EnseignantReferent',
                'verbose_name_plural': 'EnseignantsReferent',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('f', 'Feminin'), ('m', 'Masculin'), ('autre', 'Autre')])),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=120)),
            ],
            options={
                'verbose_name': 'TuteurEntreprise',
                'verbose_name_plural': 'TuteursEntreprise',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=80)),
                ('secteur', models.CharField(choices=[('technologie', 'Technologie'), ('sante', 'Sante'), ('commerce', 'Commerce')], max_length=80)),
                ('contact', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'ville'), name='unique_entreprise_nom_ville')],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('f', 'Feminin'), ('m', 'Masculin'), ('autre', 'Autre')])),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=120)),
                ('matricule', models.CharField(max_length=100)),
                ('promotion', models.PositiveIntegerField()),
                ('competences', models.ManyToManyField(related_name='etudiants', to='stages.competence')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=300)),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Nb_places', models.IntegerField()),
                ('competences', models.ManyToManyField(related_name='offres', to='stages.competence')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=100)),
                ('enseignantReferent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreferent')),
                ('etudiants', models.ManyToManyField(related_name='stages', to='stages.etudiant')),
                ('tuteurEntreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteurentreprise')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('accepte', 'ACCEPTE'), ('rejeter', 'REJETER'), ('en attente', 'EN_ATTENTE')], default=('en attente', 'EN_ATTENTE'))),
                ('date_depot', models.DateField(auto_now=True)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='stages.etudiant')),
                ('offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='stages.offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'constraints': [models.UniqueConstraint(fields=('id', 'etudiant'), name='unique_etudiant_offre')],
            },
        ),
    ]
