# Generated by Django 5.2.17 on 2026-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
