# Generated by Django 5.2.17 on 2026-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidature',
            name='unique_etudiant_offre',
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('id', 'etudiant_id'), name='unique_etudiant_offre'),
        ),
    ]
