# Generated by Django 5.2.17 on 2026-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_remove_candidature_unique_etudiant_offre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidature',
            name='unique_etudiant_offre',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('accepte', 'ACCEPTE'), ('rejeter', 'REJETER'), ('en_attente', 'EN_ATTENTE')], default='en_attente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('etudiant', 'offre'), name='unique_etudiant_offre'),
        ),
    ]
